// ignore_for_file: constant_identifier_names, non_constant_identifier_names

import 'package:flutter/material.dart';

// Base
const WHITE_COLOR = Color(0xFFFFFFFF);
const BLACK_COLOR = Color(0xFF000000);
const MEDIUM_ORCHID_COLOR = Color(0xffaa45e3);
const UNITED_NATIONS_BLUE_COLOR = Color(0xff5982e8);
const PASTEL_BLUE_COLOR = Color(0xffA1CCD1);
const BURLYWOOD_COLOR = Color(0xffE9B384);
const CULTURED_COLOR = Color(0xFFf7f7f7);
const BRIGHT_GRAY_COLOR = Color(0xFFEEEEEE);
const DIM_GRAY_COLOR = Color(0xFF686868);
const BLACK_COFFEE_COLOR = Color(0xFF332d2d);
const AWESOME_COLOR = Color(0xFFFF1744);
const GO_GREEN_COLOR = Color(0xFF00b761);
const PLATINUM_COLOR = Color(0xFFE6E6E6);
const SPIRO_DISCO_BALL_COLOR = Color(0xff2ccaf1);

// Main
const COLOR_PRIMARY = MEDIUM_ORCHID_COLOR;
const COLOR_SECONDARY = UNITED_NATIONS_BLUE_COLOR;

// Background
const BACKGROUND_LIGHT_COLOR = WHITE_COLOR;
const BACKGROUND_DARK_COLOR = BLACK_COFFEE_COLOR;

// AppBar
const APPBAR_BACKGROUND_LIGHT_COLOR = BRIGHT_GRAY_COLOR;
const APPBAR_BACKGROUND_DARK_COLOR = BLACK_COFFEE_COLOR;

// Text
const TEXT_LIGHT_COLOR = WHITE_COLOR;
const TEXT_DARK_COLOR = BLACK_COLOR;
const TEXT_GRAY_COLOR = DIM_GRAY_COLOR;
const TEXT_LINK_COLOR = SPIRO_DISCO_BALL_COLOR;
const TEXT_ERROR_COLOR = AWESOME_COLOR;
const TEXT_SUCCESS_COLOR = GO_GREEN_COLOR;

// Button
const BUTTON_BACKGROUND_COLOR = COLOR_PRIMARY;
const BUTTON_BACKGROUND_DISABLED_COLOR = PLATINUM_COLOR;

// Switch
const SWITCH_CHECKED_THUMB_COLOR = COLOR_SECONDARY;
final SWITCH_NOT_CHECKED_THUMB_COLOR = DIM_GRAY_COLOR.withOpacity(0.75);
final SWITCH_CHECKED_TRACK_COLOR = COLOR_SECONDARY.withOpacity(0.5);
final SWITCH_NOT_CHECKED_TRACK_COLOR = DIM_GRAY_COLOR.withOpacity(0.2);

// TextField
const TEXT_FIELD_BACKGROUND_LIGHT_COLOR = BRIGHT_GRAY_COLOR;
const TEXT_FIELD_BACKGROUND_DARK_COLOR = DIM_GRAY_COLOR;
const TEXT_FIELD_BORDER_LIGHT_COLOR = COLOR_PRIMARY;
const TEXT_FIELD_BORDER_DARK_COLOR = COLOR_PRIMARY;
const TEXT_FIELD_ENABLED_BORDER_LIGHT_COLOR = BRIGHT_GRAY_COLOR;
const TEXT_FIELD_ENABLED_BORDER_DARK_COLOR = BRIGHT_GRAY_COLOR;
const TEXT_FIELD_INACTIVE_COLOR = DIM_GRAY_COLOR;
final TEXT_FIELD_HINT_COLOR = TEXT_GRAY_COLOR.withOpacity(0.5);
